wasm: implement `__heap_end`
This symbol represents the end of the heap and will only be resolved
when any object file has an undefined reference to it. The symbol
is used during relocations to determine the heap end which allocators
use.